### ISSUE TITLE
Unable to locate package aerostack-melodic

### ISSUE THREAD

**Issue by str1x0** [cvar-upm/aerostack#76]
problem:
`pc@pc-VirtualBox:~$ sudo apt-get install aerostack-melodic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package aerostack-melodic
`

**Comment by pariaspe** [comment]
Aerostack is not release for ROS melodic binaries. Also, this aerostack version is no longer maintained. Please use [aerostack2](https://github.com/aerostack2/aerostack2)
